module.exports = {
  staticFeeds: [
    { name: 'Journal of Commerce', url: 'https://www.joc.com/rss', category: 'Logistics / Trade' },
    { name: 'Supply Chain Brain', url: 'https://www.supplychainbrain.com/rss', category: 'Supply Chain' },
    { name: 'Logistics Management', url: 'https://www.logisticsmgmt.com/rss.xml', category: 'Logistics' },
    { name: 'FreightWaves', url: 'https://www.freightwaves.com/feed', category: 'Freight / Logistics' },
    { name: 'Transport Topics', url: 'http://www.ttnews.com/rss.xml', category: 'Transportation' },
    { name: 'Logistics IT', url: 'https://www.logisticsit.com/rss', category: 'Supply Chain Technology' },
    { name: 'Inbound Logistics', url: 'https://www.inboundlogistics.com/rss', category: 'Logistics' },
    { name: 'Supply Chain Digital', url: 'https://supplychaindigital.com/rss', category: 'Supply Chain' },
    { name: 'DC Velocity', url: 'https://www.dcvelocity.com/rss', category: 'Warehouse / Distribution' },
    { name: 'EIN Logistics', url: 'https://shipping.einnews.com/rss', category: 'Logistics Newswire' },
    { name: 'Air Cargo News', url: 'https://www.aircargonews.net/feed', category: 'Transportation' },
    { name: 'Railway Gazette', url: 'https://www.railwaygazette.com/rss', category: 'Transportation' },
    { name: 'MarineLink', url: 'https://www.marinelink.com/rss', category: 'Transportation' },
    { name: 'Truck News', url: 'https://www.trucknews.com/feed', category: 'Transportation' },
    { name: 'IndustryWeek', url: 'https://www.industryweek.com/rss', category: 'Manufacturing' },
    { name: 'Manufacturing.net', url: 'https://www.manufacturing.net/rss', category: 'Manufacturing' },
    { name: 'Plant Engineering', url: 'https://www.plantengineering.com/rss', category: 'Manufacturing' },
    { name: 'Automation World', url: 'https://www.automationworld.com/rss', category: 'Manufacturing Automation' },
    { name: 'Field Technologies Online', url: 'https://www.fieldtechnologiesonline.com/rss', category: 'Field Service / Inventory' },
    { name: 'Field Service News', url: 'https://www.fieldservicenews.com/feed', category: 'Field Service / Inventory' },
    { name: 'PR Newswire', url: 'https://www.prnewswire.com/rss/news-releases-list.rss', category: 'Press Release' },
    { name: 'PR Newswire M&A', url: 'https://www.prnewswire.com/rss/acquisitions-mergers-takeovers/', category: 'M&A / Funding' },
    { name: 'PR.com', url: 'https://www.pr.com/rss-feeds', category: 'Press Release' },
    { name: 'Crunchbase News', url: 'https://news.crunchbase.com/feed/', category: 'Funding / Startups' },
    { name: 'PitchBook News', url: 'https://pitchbook.com/news/rss', category: 'Funding / Private Equity' },
    { name: 'Reuters Business', url: 'https://www.reutersagency.com/feed/?best-topics=business', category: 'Business News' },
    { name: 'Yahoo Finance', url: 'https://finance.yahoo.com/news/rssindex', category: 'Business News' },
    { name: 'ERP Today', url: 'https://www.erp.today/feed', category: 'ERP / Technology' },
    { name: 'Diginomica', url: 'https://diginomica.com/feed', category: 'Enterprise Technology' },
    { name: 'TechCrunch', url: 'https://techcrunch.com/feed/', category: 'Technology' },
    { name: 'USDOT', url: 'https://www.transportation.gov/rss', category: 'Government / Transportation' },
    { name: 'Bureau of Transportation Statistics', url: 'https://www.bts.gov/rss', category: 'Government / Transportation' },
    { name: 'Federal Maritime Commission', url: 'https://www.fmc.gov/feed/', category: 'Government / Maritime' },
    { name: 'GlobeNewswire M&A', url: 'https://www.globenewswire.com/RssFeed/subjectcode/27-Mergers%20And%20Acquisitions/feedTitle/GlobeNewswire%20-%20Mergers%20And%20Acquisitions', category: 'M&A / Funding' },
    { name: 'GlobeNewswire Financing', url: 'https://www.globenewswire.com/RssFeed/subjectcode/17-Financing%20Agreements/feedTitle/GlobeNewswire%20-%20Financing%20Agreements', category: 'M&A / Funding' },
    { name: 'GlobeNewswire Management Changes', url: 'https://www.globenewswire.com/RssFeed/subjectcode/86-Management%20Changes/feedTitle/GlobeNewswire%20-%20Management%20Changes', category: 'Management Change' },
    { name: 'GlobeNewswire Press Releases', url: 'https://www.globenewswire.com/RssFeed/subjectcode/72-Press%20Releases/feedTitle/GlobeNewswire%20-%20Press%20Releases', category: 'Press Release' },
    { name: 'ACCESS Newswire', url: 'https://www.accesswire.com/rssfeed.aspx', category: 'Press Release' },
    { name: 'Newswire Supply Chain', url: 'https://www.newswire.com/newsroom/rss/beat/business-supply-chain-management', category: 'Supply Chain Newswire' },
    { name: 'Newswire Transportation & Logistics', url: 'https://www.newswire.com/newsroom/rss/beat/business-transportation-and-logistics', category: 'Transportation Newswire' },
    { name: 'Newswire Warehousing', url: 'https://www.newswire.com/newsroom/rss/beat/business-warehousing', category: 'Warehouse Newswire' },
    { name: 'Google News Inventory Management', url: 'https://news.google.com/rss/search?q=inventory%20management&hl=en-US&gl=US&ceid=US:en', category: 'Google News' },
    { name: 'Google News Warehouse Management', url: 'https://news.google.com/rss/search?q=warehouse%20management&hl=en-US&gl=US&ceid=US:en', category: 'Google News' },
    { name: 'Google News Warehouse Automation', url: 'https://news.google.com/rss/search?q=warehouse%20automation&hl=en-US&gl=US&ceid=US:en', category: 'Google News' },
    { name: 'Google News Distribution Center', url: 'https://news.google.com/rss/search?q=distribution%20center&hl=en-US&gl=US&ceid=US:en', category: 'Google News' },
    { name: 'Google News Supply Chain Disruption', url: 'https://news.google.com/rss/search?q=supply%20chain%20disruption&hl=en-US&gl=US&ceid=US:en', category: 'Google News' },
    { name: 'Google News Manufacturing Automation', url: 'https://news.google.com/rss/search?q=manufacturing%20automation&hl=en-US&gl=US&ceid=US:en', category: 'Google News' },
    { name: 'Google News RFID Inventory', url: 'https://news.google.com/rss/search?q=RFID%20inventory&hl=en-US&gl=US&ceid=US:en', category: 'Google News' },
    { name: 'Google News WMS', url: 'https://news.google.com/rss/search?q=%22warehouse%20management%20system%22&hl=en-US&gl=US&ceid=US:en', category: 'Google News' },
    { name: 'Google News TMS', url: 'https://news.google.com/rss/search?q=%22transportation%20management%20system%22&hl=en-US&gl=US&ceid=US:en', category: 'Google News' },
    { name: 'Google News 3PL Warehousing', url: 'https://news.google.com/rss/search?q=3PL%20warehousing&hl=en-US&gl=US&ceid=US:en', category: 'Google News' },
    { name: 'Google News Cold Chain Logistics', url: 'https://news.google.com/rss/search?q=cold%20chain%20logistics&hl=en-US&gl=US&ceid=US:en', category: 'Google News' },
    { name: 'Google News Field Inventory', url: 'https://news.google.com/rss/search?q=%22field%20inventory%22&hl=en-US&gl=US&ceid=US:en', category: 'Google News' },
    { name: 'Google News Supply Chain Recruiting', url: 'https://news.google.com/rss/search?q=supply%20chain%20recruiting&hl=en-US&gl=US&ceid=US:en', category: 'Google News' }
  ]
};
